# Generated by Django 5.2.5 on 2025-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.AddField(
            model_name='ticket',
            name='content',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Image'),
        ),
    ]
