# Generated by Django 5.2.5 on 2025-10-24 15:36

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_description_ticket_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tickets.models.ticket_image_upload_path, verbose_name='Image'),
        ),
    ]
